package ru.gamechatbot.puzzlevibergames.viber;

import java.util.Arrays;
import java.util.Iterator;
import java.util.List;
import java.util.stream.IntStream;

public class Keyboards {
    public Keyboard menu() {
        return new Keyboard.KeyboardBuilder()

                .addButton(new Button.ButtonBuilder("tictactoe-game", "reply")
                        .text("Крестики-нолики")
                        .textColor("#F0F8FF")
                        .textSize(20)
                        .bgColor("#00CED1")
                        .columns(6)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag-game", "reply")
                        .text("Пятнашки")
                        .textColor("#F0F8FF")
                        .textSize(20)
                        .bgColor("#00BFFF")
                        .columns(6)
                        .rows(1)
                        .build())

                .addButton(new Button.ButtonBuilder("guessing-game", "reply")
                        .text("Угадайка")
                        .textColor("#F0F8FF")
                        .textSize(20)
                        .bgColor("#1E90FF")
                        .columns(6)
                        .rows(1)
                        .build())

                .addButton(new Button.ButtonBuilder("balda-game", "reply")
                        .text("Балда")
                        .textColor("#F0F8FF")
                        .textSize(20)
                        .bgColor("#6A5ACD")
                        .columns(6)
                        .rows(1)
                        .build())
                .build();
    }

    public Keyboard tagGameKeyboard(List<String> values, List<String > colors) {
        return new Keyboard.KeyboardBuilder()

                .addButton(new Button.ButtonBuilder("tag_0", "reply")
                        .text(String.valueOf(values.get(0)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(0))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_1", "reply")
                        .text(String.valueOf(values.get(1)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(1))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_2", "reply")
                        .text(String.valueOf(values.get(2)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(2))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_3", "reply")
                        .text(String.valueOf(values.get(3)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(3))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag-game", "reply")
                        .text("Новая игра")
                        .textColor("#E9967A")
                        .textSize(12)
                        .bgColor("#F0FFF0")
                        .columns(2)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_4", "reply")
                        .text(String.valueOf(values.get(4)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(4))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_5", "reply")
                        .text(String.valueOf(values.get(5)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(5))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_6", "reply")
                        .text(String.valueOf(values.get(6)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(6))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_7", "reply")
                        .text(String.valueOf(values.get(7)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(7))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("game-menu", "reply")
                        .text("К другим играм")
                        .textColor("#8FBC8F")
                        .textSize(12)
                        .bgColor("#F8F8FF")
                        .columns(2)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_8", "reply")
                        .text(String.valueOf(values.get(8)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(8))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_9", "reply")
                        .text(String.valueOf(values.get(9)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(9))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_10", "reply")
                        .text(String.valueOf(values.get(10)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(10))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_11", "reply")
                        .text(String.valueOf(values.get(11)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(11))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("start-menu", "reply")
                        .text("В стартовое меню")
                        .textColor("#00BFFF")
                        .textSize(12)
                        .bgColor("#E6E6FA")
                        .columns(2)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_12", "reply")
                        .text(String.valueOf(values.get(12)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(12))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_13", "reply")
                        .text(String.valueOf(values.get(13)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(13))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_14", "reply")
                        .text(String.valueOf(values.get(14)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(14))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tag_15", "reply")
                        .text(String.valueOf(values.get(15)))
                        .silent("True")
                        .textColor("#f7f0ff")
                        .textSize(16)
                        .bgColor(colors.get(15))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("", "none")
                        .text("")
                        .silent("True")
                        .textColor("#00BFFF")
                        .bgColor("#E6E6FA")
                        .columns(2)
                        .rows(1)
                        .build())
                .build();
    }

    public Keyboard startGameMemuButton() {
        return new Keyboard.KeyboardBuilder()
                .addButton(new Button.ButtonBuilder("game-menu", "reply")
                        .text("Игры")
                        .textColor("#00000F")
                        .textSize(24)
                        .bgColor("#FFFFF0")
                        .columns(6)
                        .rows(1)
                        .build())
                .build();
    }

    public RichKeyboard calendar() {
        RichKeyboard.RichKeyboardBuilder buttons = new RichKeyboard.RichKeyboardBuilder();
        ViberCalendar viberCalendar = new ViberCalendar();
        List<String> month = viberCalendar.seq_num_month(1,2021);
        Iterator<String> iterator = month.iterator();
        IntStream.range(1, 43).forEach(i -> {
            String bgColor = "#FFFFFF";
            String text = String.valueOf(i);
            if (i > 30)
                bgColor = "#FF0000";
            if (iterator.hasNext())
                text = iterator.next();

            buttons.addButton(
                    new Button.ButtonBuilder("Время", "reply")
                            .text(text)
                            .textColor("#00000F")
                            .textSize(24)
                            .bgColor(bgColor)
                            .columns(1)
                            .rows(1)
                            .build());
        });
        return buttons.build();
    }

    public Keyboard ticTacToeKeyboard(List<String> textArray, List<String> bgColors) {
        List<String> actionTypes = Arrays.asList("reply", "reply", "reply", "reply", "reply", "reply", "reply", "reply", "reply");
        for (int i = 0; i < textArray.size(); i++) {
            String s = textArray.get(i);
            if (!s.isEmpty()) {
                actionTypes.set(i, "none");
            }
        }
        return new Keyboard.KeyboardBuilder()

                .addButton(new Button.ButtonBuilder("empty_cell_0", actionTypes.get(0))
                        .text(textArray.get(0))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(0))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder( "empty_cell_1", actionTypes.get(1))
                        .text(textArray.get(1))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(1))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("empty_cell_2", actionTypes.get(2))
                        .text(textArray.get(2))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(2))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("tictactoe-game", "reply")
                        .text("Новая игра")
                        .textColor("#E9967A")
                        .textSize(12)
                        .bgColor("#F0FFF0")
                        .columns(3)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("empty_cell_3", actionTypes.get(3))
                        .text(textArray.get(3))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(3))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder( "empty_cell_4", actionTypes.get(4))
                        .text(textArray.get(4))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(4))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("empty_cell_5", actionTypes.get(5))
                        .text(textArray.get(5))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(5))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("game-menu", "reply")
                        .text("К другим играм")
                        .textColor("#8FBC8F")
                        .textSize(12)
                        .bgColor("#F8F8FF")
                        .columns(3)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("empty_cell_6", actionTypes.get(6))
                        .text(textArray.get(6))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(6))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder( "empty_cell_7", actionTypes.get(7))
                        .text(textArray.get(7))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(7))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("empty_cell_8", actionTypes.get(8))
                        .text(textArray.get(8))
                        .silent("True")
                        .textColor("#000000")
                        .textSize(24)
                        .bgColor(bgColors.get(8))
                        .columns(1)
                        .rows(1)
                        .build())
                .addButton(new Button.ButtonBuilder("start-menu", "reply")
                        .text("В стартовое меню")
                        .textColor("#00BFFF")
                        .textSize(12)
                        .bgColor("#E6E6FA")
                        .columns(3)
                        .rows(1)
                        .build())
                .build();


    }
}